server:
  port: 6000
spring:
  application:
      name: country-details

  datasource:
    url: jdbc:mysql://localhost:3306/cd_users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
    hibernate:
#      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#logging:
#  level:
#    root: trace
